'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
fibo = [1,2]
current = 0
done = False
index=1

#fibo[1] have even number so initially set sum to this value
sum = fibo[1]

while not done:
  current = fibo[index-1]+fibo[index]

  #Check if the term value exceeds 4million or not
  if current<=4000000:
    index=index+1
    fibo.append(current)

    '''Check if the determined value is even or not
      if yes => add the number to sum
      if no => donot add
    '''
    if current%2==0:
      temp = sum
      sum = sum + current
      print(f"Adding:{temp} with {current} ==> {sum}")

  else:
    done = True
    break


print(fibo)
print(sum)

